code --install-extension HookyQR.beautify
code --install-extension JPTarquino.postgresql
code --install-extension KnisterPeter.vscode-github
code --install-extension LaurentTreguier.vscode-simple-icons
code --install-extension PKief.material-icon-theme
code --install-extension akamud.vscode-theme-onedark
code --install-extension azemoh.one-monokai
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension doublefint.pgsql
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension felixfbecker.php-debug
code --install-extension file-icons.file-icons
code --install-extension gerane.Theme-FlatlandMonokai
code --install-extension ivangabriele.vscode-tfs
code --install-extension jakeboone02.cypher-query-language
code --install-extension jchannon.csharpextensions
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension vscodevim.vim
code --install-extension whatwedo.twig
