alias ls='ls --color'
alias werk='cd /home/matthew/Projects/networth/'
alias brave='brave --ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --disable-gpu-driver-bug-workarounds --use-gl=egl --enable-accelerated-video-decode'
alias assh='ssh -i ~/.keys/aws.a---.pem'
alias assh='ssh -i ~/keys/aws.a---.pem'
alias nssh='ssh -i ~/.keys/aws.n--.pem'
alias nscp='scp -i ~/.keys/aws.n--.pem'
alias grep='grep -s --exclude-dir=node_modules --exclude-dir=.git --exclude=bundle.js --exclude=package-lock.json --color=always'
alias ll='ls -al'
alias youtube='firefox --new-window https://www.youtube.com'
alias cb='xclip -sel clip'
alias cam='mpv av://v4l2:/dev/video0'
neofetch
